# Generated by Django 5.2.4 on 2025-07-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fax1',
            new_name='fax',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fax2',
            new_name='phone2',
        ),
    ]
