# Generated by Django 5.2.4 on 2025-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_fax1_contact_fax_rename_phone_contact_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gramm',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductWeight',
        ),
    ]
