# Generated by Django 5.2.4 on 2025-07-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_category_created_at_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='document',
        ),
    ]
