# Generated by Django 5.2.4 on 2025-07-16 17:41

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_certification_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, optional +, space or dash).', regex='^\\+?[\\d\\s\\-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, optional +, space or dash).', regex='^\\+?[\\d\\s\\-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, optional +, space or dash).', regex='^\\+?[\\d\\s\\-]{7,20}$')]),
        ),
        migrations.CreateModel(
            name='ContactTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dashboard.contact')),
            ],
            options={
                'verbose_name': 'contact Translation',
                'db_table': 'dashboard_contact_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
