# Generated by Django 5.2.4 on 2025-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_contact_address_alter_contact_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='dashboard.category'),
        ),
    ]
